import { NextResponse } from 'next/server';

export const dynamic = 'force-dynamic';

export async function POST() {
  return NextResponse.json(
    {
      error: 'Unsupported backend capability',
      detail: 'The authoritative backend checked into manikumarkundena/permisense-ics does not expose /api/demo/scenarios/speed. No synthetic incident is generated by the frontend.',
    },
    { status: 501 }
  );
}
